config/routes.rb
SampleSfdcApp::Application.routes.draw do
  resources :merchandise__c, :path => '/merchandise',:controller => "merchandise"
  resources :merchandise__cs, :path => '/merchandise',:controller => "merchandise"
  resources :merchandise
  get "merchandise/index"
  get "merchandise/create"
  get "merchandise/show"
  get "merchandise/edit"
  get "merchandise/update"
  
  resources :accounts
  

  resources :users
  get "user/index"
  get "user/new"
  get "user/create"
  root :to => "accounts#index"
  

end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  include Databasedotcom::Rails::Controller
    
  def index
    @accounts = Account.all
  end

  def show
    @account = Account.find(params[:id])
  end

  def new
    @account = Account.new   #"ParentId"=>Account.first.Id
  end
  
  def create
      account=Account.new(params[:account])
      account.OwnerId=User.first.Id
      account.Med_Consult_Requested__c=false
      #Account.create Account.coerce_params(params[:account])
      begin
        if (account.save)
          redirect_to(account, :notice => 'Account was successfully created.')
        end
      rescue Databasedotcom::SalesForceError => e
          redirect_to(accounts_path, :notice => "Error creating account: #{e.message}")
      end
  end

  def edit
    @account = Account.find(params[:id])
  end
  
  def update
    @account = Account.find(params[:id])
    @account.update_attributes(params[:account])
    render "show"
  end  
  
  
  
end

app/controllers/accounts_controller.sample.Jeff.rb
class AccountsController < ApplicationController

  include Databasedotcom::Rails::Controller

  # GET /accounts
  def index
    @accounts = Account__c.all
  end

  # GET /accounts/1
  def show
    @account = Account__c.find(params[:id])
  end

  # GET /accounts/new
  def new
    @account = Account__c.new
  end

  # GET /accounts/1/edit
  def edit
    @account = Account__c.find(params[:id])
  end

  # POST /accounts
  def create
    @account = Account__c.new(params[:account])
    # fetch the id of any user as the 'owner' - required by sfdc
    @account.OwnerId = User.first.Id

    if @account.save
      redirect_to account_path(@account), notice: 'Account was successfully created.'
    else
      format.html { render action: "new" }
    end
  end

  # this action throws following error: https://gist.github.com/1428406
  # PUT /accounts/1
  def update
    @account = Account__c.find(params[:id])

    begin
      @account.update_attributes Account__c.coerce_params(params[:account])
      notice = 'Account updated successfully'
    rescue Databasedotcom::SalesForceError => e
      notice = 'Could not update record!!'
    end

    redirect_to account_path(@account), notice: notice
  end

  # DELETE /accounts/1
  def destroy
    @account = Account__c.find(params[:id])
    @account.destroy

    respond_to do |format|
      format.html { redirect_to accounts_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/merchandise_controller.rb
class MerchandiseController < ApplicationController
  include Databasedotcom::Rails::Controller
  
  def index
    @merchandise = Merchandise__c.all
  end
  
  def show
    @merchandise = Merchandise__c.find(params[:id])
  end
  
  def new
    @merchandise = Merchandise__c.new   #"ParentId"=>Account.first.Id
  end

  def create
    merchandise = Merchandise__c.new(params[:merchandise__c])
    merchandise.OwnerId = User.first.Id
    #Account.create Account.coerce_params(params[:account])
    begin
      if (merchandise.save)
        redirect_to(merchandise, :notice => 'Merchandise was successfully created.')
      end
    rescue Databasedotcom::SalesForceError => e
        redirect_to(merchandise_index_path, :notice => "Error creating merchandise: #{e.message}")
    end
  end

  def edit
    @merchandise = Merchandise__c.find(params[:id])
  end

    
  def update
        @merchandise = Merchandise__c.find(params[:id])
        #raise params.inspect
        @merchandise.Name = params[:merchandise__c][:Name]
        @merchandise.Price__c = params[:merchandise__c][:Price__c]
        @merchandise.Quantity__c = params[:merchandise__c][:Quantity__c]
        
        begin
          if (@merchandise.save)
            redirect_to(@merchandise, :notice => 'Merchandise was successfully updated.')
          end
        rescue Databasedotcom::SalesForceError => e
            redirect_to(merchandise_path, :notice => "Error updating merchandise: #{e.message}")
        end
    
    #@merchandise = Merchandise__c.find(params[:id])
    #@merchandise.update_attributes(params[:merchandise])
    #render "show"
  end
  
  
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  include Databasedotcom::Rails::Controller
  def index
    @users = User.all
  end

  def new
  end

  def create
  end
end

app/helpers/account_helper.rb
module AccountHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/merchandises_helper.rb
module MerchandisesHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/accounts/edit.html.erb
<h1>Update Account</h1>

<% if flash[:notice] %>
  <%= flash[:notice] %><br/><br/>
<% end %>

<%= form_for @account do |f| %>
    <div class="field">
        <%= f.label :Name %><br />
        <%= f.text_field :Name%>
    </div>
    <div class="field">
        <%= f.label "Type" %>
        <%= f.select :Type, options_for_select([['Prospect', 'Prospect'], ['Store', 'Store'], ['Other','Other']]) %>
    </div>
    <div class="actions">
        <%= f.submit %>
    </div>
<% end %>

<br/>

<%= link_to 'Back', accounts_path %>

app/views/accounts/index.html.erb
<h1>Account#index</h1>

<% if flash[:notice] %>
  <%= flash[:notice] %><br/><br/>
<% end %>
<ul>
	<% @accounts.each do |account|%>
	<li><%= link_to "#{account.Name}", account%> (<%=link_to "Edit", edit_account_path(account) %>)</li>
	<%end%>
</ul>

app/views/accounts/new.html.erb
<h1>Create Account</h1>

<% if flash[:notice] %>
  <%= flash[:notice] %><br/><br/>
<% end %>

<%= form_for @account do |f| %>
    <div class="field">
        <%= f.label :Name %><br />
        <%= f.text_field :Name%>
    </div>
    <div class="field">
        <%= f.label "Type" %>
        <%= f.select :Type, options_for_select([['Prospect', 'Prospect'], ['Store', 'Store'], ['Other','Other']]) %>
    </div>
    <div class="actions">
        <%= f.submit %>
    </div>
<% end %>

<br/>

<%= link_to 'Back', accounts_path %>

app/views/accounts/show.html.erb
<h1>Account <%= @account.Name %></h1>

<%= link_to 'Edit', edit_account_path(@account) %> |
<%= link_to 'Back', accounts_path %>
<br/>
<br/>

<% @account.attributes.each do |a| %>
    <%= a[0] %>: <%= a[1] %><br/>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SampleSfdcApp</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/merchandise/edit.html.erb
<h1>Update Merchandise</h1>

<% if flash[:notice] %>
  <%= flash[:notice] %><br/><br/>
<% end %>

<%= form_for(@merchandise, format: :json) do |f| %>
    <div class="field">
        <%= f.label :Name %><br />
        <%= f.text_field :Name%>
    </div>

    <div class="field">
        <%= f.label "Quantity" %>
        <%= f.number_field :Quantity__c %>
    </div>

	<div class="field">
        <%= f.label "Price" %>
        <%= f.number_field :Price__c %>
    </div>

    <div class="actions">
        <%= f.button "Submit",:name=>"Content-Type",:value=>"application/json"%>
    </div>
<% end %>

<br/>

<%= link_to 'Back', merchandise_path %>

app/views/merchandise/index.html.erb
<h1>Merchandise Listing</h1>

<% if flash[:notice] %>
  <%= flash[:notice] %><br/><br/>
<% end %>
<ul>
	<% @merchandise.each do |m|%>
	<li><%= link_to "#{m.Name}", m%> (<%=link_to "Edit", edit_merchandise_path(m) %>)</li>
	
	<%end%>
</ul>

app/views/merchandise/new.html.erb
<h1>New Merchandise</h1>

<% if flash[:notice] %>
  <%= flash[:notice] %><br/><br/>
<% end %>

<%= form_for @merchandise do |f| %>
    <div class="field">
        <%= f.label :Name %><br />
        <%= f.text_field :Name%>
    </div>

    <div class="field">
        <%= f.label "Quantity" %>
        <%= f.number_field :Quantity__c %>
    </div>

	<div class="field">
        <%= f.label "Price" %>
        <%= f.number_field :Price__c %>
    </div>

    <div class="actions">
        <%= f.submit %>
    </div>
<% end %>

<br/>

<%= link_to 'Back', accounts_path %>

app/views/merchandise/show.html.erb
<h1>Merchandise: <%= @merchandise.Name %></h1>
<% if flash[:notice] %>
  <%= flash[:notice] %><br/><br/>
<% end %>

<%= link_to 'Edit', edit_merchandise_path(@merchandise) %> |
<%= link_to 'List', merchandise_index_path %>
<br/>
<br/>

<% @merchandise.attributes.each do |a| %>
    <%= a[0] %>: <%= a[1] %><br/>
<% end %>

app/views/user/create.html.erb
<h1>User#create</h1>
<p>Find me in app/views/user/create.html.erb</p>

app/views/user/index.html.erb
<ul>
	<% @users.each do |user|%>
	<li><%= user.Name%></li>
	<%end%>
</ul>

app/views/user/new.html.erb
<h1>User#new</h1>
<p>Find me in app/views/user/new.html.erb</p>